/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Business.TicketGenerator;
import Interfaces.FrameInterface;
import Interfaces.FrameManagerInterface;
import java.nio.file.Path;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author leonardoalvesdemelo
 */
public class CreateTicketPanel extends javax.swing.JPanel implements FrameInterface {

    FrameManagerInterface manager;
    ArrayList<String[]> selectedPouchs;
    
    @Override
    public void setManager(FrameManagerInterface manager) {
        this.manager = manager;
    }

    /**
     * Creates new form CreateTicketPanel
     */
    public CreateTicketPanel(ArrayList<String[]> selectedPouchs) {
        this.selectedPouchs = selectedPouchs;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        loadingLabel = new javax.swing.JLabel();

        jButton1.setText("Cria PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        loadingLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(loadingLabel)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingLabel)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.loadingLabel.setText("Gerando Tickets...");
        
        String pathString = "files/teste.pdf";
        
        JFileChooser openFile = new JFileChooser();
        int result = openFile.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            Path path = openFile.getSelectedFile().toPath();
            pathString = path.toString();
        }
        
        TicketGenerator generator = new TicketGenerator(pathString);
        
        generator.generatePage(selectedPouchs);
        this.loadingLabel.setText("Tickets Gerados!");
        JOptionPane.showMessageDialog(null, "Ticket(s) criado(s) com sucesso! Veja-o(s) em \"" +  pathString + ".pdf\"!");
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel loadingLabel;
    // End of variables declaration//GEN-END:variables
}
