/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Business.DatabaseServices;
import Interfaces.FrameInterface;
import Interfaces.FrameManagerInterface;
import Model.TableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author leonardoalvesdemelo
 */
public class PouchListPanel extends javax.swing.JPanel implements FrameInterface {

    FrameManagerInterface manager;
    String fileName;
    DatabaseServices databaseServices;
    
    @Override
    public void setManager(FrameManagerInterface manager) {
        this.manager = manager;
    }

    /**
     * Creates new form PouchListPanel
     */
    public PouchListPanel(String fileName, String transportatorName) {
        this.fileName = fileName;
        this.databaseServices = new DatabaseServices();
        this.databaseServices.setDatabase(fileName, transportatorName);
        initComponents();
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Lista de Malotes");

        jButton1.setText("Selecionar Todos");

        jButton2.setText("Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonTapped(evt);
            }
        });

        jTable1.setModel(new TableModel(this.databaseServices));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonTapped(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonTapped
        /* Se não selecionou nenhuma empresa */
        if(this.jTable1.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione pelo menos um malote para continuar!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        /* Se selecionaram */
        else {
            
            /* Determina qual foi a escolha */
            int[] rows = this.jTable1.getSelectedRows();
            
            ArrayList<String[]> selectedPouchs = new ArrayList<String[]>();
            
            for(int i = 0; i < rows.length; i++) {
                selectedPouchs.add(this.databaseServices.getDatabase().get(rows[i]));
            }
            
            this.manager.changeCurrentPanel(new CreateTicketPanel(selectedPouchs));
            
            
            
        }
    }//GEN-LAST:event_continueButtonTapped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
